//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EX.Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisitorDTO", Namespace="http://iterator.org")]
    [System.SerializableAttribute()]
    public partial class VisitorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Column9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column1 {
            get {
                return this.Column1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column1Field, value) != true)) {
                    this.Column1Field = value;
                    this.RaisePropertyChanged("Column1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column10 {
            get {
                return this.Column10Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column10Field, value) != true)) {
                    this.Column10Field = value;
                    this.RaisePropertyChanged("Column10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column11 {
            get {
                return this.Column11Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column11Field, value) != true)) {
                    this.Column11Field = value;
                    this.RaisePropertyChanged("Column11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column12 {
            get {
                return this.Column12Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column12Field, value) != true)) {
                    this.Column12Field = value;
                    this.RaisePropertyChanged("Column12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column13 {
            get {
                return this.Column13Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column13Field, value) != true)) {
                    this.Column13Field = value;
                    this.RaisePropertyChanged("Column13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column14 {
            get {
                return this.Column14Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column14Field, value) != true)) {
                    this.Column14Field = value;
                    this.RaisePropertyChanged("Column14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column15 {
            get {
                return this.Column15Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column15Field, value) != true)) {
                    this.Column15Field = value;
                    this.RaisePropertyChanged("Column15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column2 {
            get {
                return this.Column2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column2Field, value) != true)) {
                    this.Column2Field = value;
                    this.RaisePropertyChanged("Column2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column3 {
            get {
                return this.Column3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column3Field, value) != true)) {
                    this.Column3Field = value;
                    this.RaisePropertyChanged("Column3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column4 {
            get {
                return this.Column4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column4Field, value) != true)) {
                    this.Column4Field = value;
                    this.RaisePropertyChanged("Column4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column5 {
            get {
                return this.Column5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column5Field, value) != true)) {
                    this.Column5Field = value;
                    this.RaisePropertyChanged("Column5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column6 {
            get {
                return this.Column6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column6Field, value) != true)) {
                    this.Column6Field = value;
                    this.RaisePropertyChanged("Column6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column7 {
            get {
                return this.Column7Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column7Field, value) != true)) {
                    this.Column7Field = value;
                    this.RaisePropertyChanged("Column7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column8 {
            get {
                return this.Column8Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column8Field, value) != true)) {
                    this.Column8Field = value;
                    this.RaisePropertyChanged("Column8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Column9 {
            get {
                return this.Column9Field;
            }
            set {
                if ((object.ReferenceEquals(this.Column9Field, value) != true)) {
                    this.Column9Field = value;
                    this.RaisePropertyChanged("Column9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentStatus {
            get {
                return this.CurrentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentStatusField, value) != true)) {
                    this.CurrentStatusField = value;
                    this.RaisePropertyChanged("CurrentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusDTO", Namespace="http://iterator.org")]
    [System.SerializableAttribute()]
    public partial class StatusDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VisitorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionTime {
            get {
                return this.ActionTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTimeField, value) != true)) {
                    this.ActionTimeField = value;
                    this.RaisePropertyChanged("ActionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VisitorId {
            get {
                return this.VisitorIdField;
            }
            set {
                if ((this.VisitorIdField.Equals(value) != true)) {
                    this.VisitorIdField = value;
                    this.RaisePropertyChanged("VisitorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInRoleDTO", Namespace="http://schemas.datacontract.org/2004/07/EX.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class UserInRoleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/EX.Model.DTO")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVisitorContract")]
    public interface IVisitorContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllVisitors", ReplyAction="http://tempuri.org/IVisitorContract/GetAllVisitorsResponse")]
        EX.Client.ServiceReference1.VisitorDTO[] GetAllVisitors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllVisitors", ReplyAction="http://tempuri.org/IVisitorContract/GetAllVisitorsResponse")]
        System.Threading.Tasks.Task<EX.Client.ServiceReference1.VisitorDTO[]> GetAllVisitorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetVisitorById", ReplyAction="http://tempuri.org/IVisitorContract/GetVisitorByIdResponse")]
        EX.Client.ServiceReference1.VisitorDTO GetVisitorById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetVisitorById", ReplyAction="http://tempuri.org/IVisitorContract/GetVisitorByIdResponse")]
        System.Threading.Tasks.Task<EX.Client.ServiceReference1.VisitorDTO> GetVisitorByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/AddOrUpdateVisitor", ReplyAction="http://tempuri.org/IVisitorContract/AddOrUpdateVisitorResponse")]
        EX.Client.ServiceReference1.VisitorDTO AddOrUpdateVisitor(EX.Client.ServiceReference1.VisitorDTO visitor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/AddOrUpdateVisitor", ReplyAction="http://tempuri.org/IVisitorContract/AddOrUpdateVisitorResponse")]
        System.Threading.Tasks.Task<EX.Client.ServiceReference1.VisitorDTO> AddOrUpdateVisitorAsync(EX.Client.ServiceReference1.VisitorDTO visitor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveVisitor", ReplyAction="http://tempuri.org/IVisitorContract/RemoveVisitorResponse")]
        void RemoveVisitor(EX.Client.ServiceReference1.VisitorDTO visitor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveVisitor", ReplyAction="http://tempuri.org/IVisitorContract/RemoveVisitorResponse")]
        System.Threading.Tasks.Task RemoveVisitorAsync(EX.Client.ServiceReference1.VisitorDTO visitor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveVisitorById", ReplyAction="http://tempuri.org/IVisitorContract/RemoveVisitorByIdResponse")]
        void RemoveVisitorById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveVisitorById", ReplyAction="http://tempuri.org/IVisitorContract/RemoveVisitorByIdResponse")]
        System.Threading.Tasks.Task RemoveVisitorByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/AddStatus", ReplyAction="http://tempuri.org/IVisitorContract/AddStatusResponse")]
        void AddStatus(EX.Client.ServiceReference1.StatusDTO status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/AddStatus", ReplyAction="http://tempuri.org/IVisitorContract/AddStatusResponse")]
        System.Threading.Tasks.Task AddStatusAsync(EX.Client.ServiceReference1.StatusDTO status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveStatus", ReplyAction="http://tempuri.org/IVisitorContract/RemoveStatusResponse")]
        void RemoveStatus(EX.Client.ServiceReference1.StatusDTO status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveStatus", ReplyAction="http://tempuri.org/IVisitorContract/RemoveStatusResponse")]
        System.Threading.Tasks.Task RemoveStatusAsync(EX.Client.ServiceReference1.StatusDTO status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllStatuses", ReplyAction="http://tempuri.org/IVisitorContract/GetAllStatusesResponse")]
        EX.Client.ServiceReference1.StatusDTO[] GetAllStatuses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllStatuses", ReplyAction="http://tempuri.org/IVisitorContract/GetAllStatusesResponse")]
        System.Threading.Tasks.Task<EX.Client.ServiceReference1.StatusDTO[]> GetAllStatusesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/AddUserInRole", ReplyAction="http://tempuri.org/IVisitorContract/AddUserInRoleResponse")]
        void AddUserInRole(EX.Client.ServiceReference1.UserInRoleDTO userInRoleDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/AddUserInRole", ReplyAction="http://tempuri.org/IVisitorContract/AddUserInRoleResponse")]
        System.Threading.Tasks.Task AddUserInRoleAsync(EX.Client.ServiceReference1.UserInRoleDTO userInRoleDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveUserInRole", ReplyAction="http://tempuri.org/IVisitorContract/RemoveUserInRoleResponse")]
        void RemoveUserInRole(EX.Client.ServiceReference1.UserInRoleDTO userInRoleDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveUserInRole", ReplyAction="http://tempuri.org/IVisitorContract/RemoveUserInRoleResponse")]
        System.Threading.Tasks.Task RemoveUserInRoleAsync(EX.Client.ServiceReference1.UserInRoleDTO userInRoleDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllUserInRole", ReplyAction="http://tempuri.org/IVisitorContract/GetAllUserInRoleResponse")]
        EX.Client.ServiceReference1.UserInRoleDTO[] GetAllUserInRole();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllUserInRole", ReplyAction="http://tempuri.org/IVisitorContract/GetAllUserInRoleResponse")]
        System.Threading.Tasks.Task<EX.Client.ServiceReference1.UserInRoleDTO[]> GetAllUserInRoleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/AddUser", ReplyAction="http://tempuri.org/IVisitorContract/AddUserResponse")]
        void AddUser(EX.Client.ServiceReference1.UserDTO userDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/AddUser", ReplyAction="http://tempuri.org/IVisitorContract/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(EX.Client.ServiceReference1.UserDTO userDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveUser", ReplyAction="http://tempuri.org/IVisitorContract/RemoveUserResponse")]
        void RemoveUser(EX.Client.ServiceReference1.UserDTO userDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/RemoveUser", ReplyAction="http://tempuri.org/IVisitorContract/RemoveUserResponse")]
        System.Threading.Tasks.Task RemoveUserAsync(EX.Client.ServiceReference1.UserDTO userDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllUsers", ReplyAction="http://tempuri.org/IVisitorContract/GetAllUsersResponse")]
        EX.Client.ServiceReference1.UserDTO[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitorContract/GetAllUsers", ReplyAction="http://tempuri.org/IVisitorContract/GetAllUsersResponse")]
        System.Threading.Tasks.Task<EX.Client.ServiceReference1.UserDTO[]> GetAllUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVisitorContractChannel : EX.Client.ServiceReference1.IVisitorContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisitorContractClient : System.ServiceModel.ClientBase<EX.Client.ServiceReference1.IVisitorContract>, EX.Client.ServiceReference1.IVisitorContract {
        
        public VisitorContractClient() {
        }
        
        public VisitorContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisitorContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitorContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitorContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EX.Client.ServiceReference1.VisitorDTO[] GetAllVisitors() {
            return base.Channel.GetAllVisitors();
        }
        
        public System.Threading.Tasks.Task<EX.Client.ServiceReference1.VisitorDTO[]> GetAllVisitorsAsync() {
            return base.Channel.GetAllVisitorsAsync();
        }
        
        public EX.Client.ServiceReference1.VisitorDTO GetVisitorById(int Id) {
            return base.Channel.GetVisitorById(Id);
        }
        
        public System.Threading.Tasks.Task<EX.Client.ServiceReference1.VisitorDTO> GetVisitorByIdAsync(int Id) {
            return base.Channel.GetVisitorByIdAsync(Id);
        }
        
        public EX.Client.ServiceReference1.VisitorDTO AddOrUpdateVisitor(EX.Client.ServiceReference1.VisitorDTO visitor) {
            return base.Channel.AddOrUpdateVisitor(visitor);
        }
        
        public System.Threading.Tasks.Task<EX.Client.ServiceReference1.VisitorDTO> AddOrUpdateVisitorAsync(EX.Client.ServiceReference1.VisitorDTO visitor) {
            return base.Channel.AddOrUpdateVisitorAsync(visitor);
        }
        
        public void RemoveVisitor(EX.Client.ServiceReference1.VisitorDTO visitor) {
            base.Channel.RemoveVisitor(visitor);
        }
        
        public System.Threading.Tasks.Task RemoveVisitorAsync(EX.Client.ServiceReference1.VisitorDTO visitor) {
            return base.Channel.RemoveVisitorAsync(visitor);
        }
        
        public void RemoveVisitorById(int Id) {
            base.Channel.RemoveVisitorById(Id);
        }
        
        public System.Threading.Tasks.Task RemoveVisitorByIdAsync(int Id) {
            return base.Channel.RemoveVisitorByIdAsync(Id);
        }
        
        public void AddStatus(EX.Client.ServiceReference1.StatusDTO status) {
            base.Channel.AddStatus(status);
        }
        
        public System.Threading.Tasks.Task AddStatusAsync(EX.Client.ServiceReference1.StatusDTO status) {
            return base.Channel.AddStatusAsync(status);
        }
        
        public void RemoveStatus(EX.Client.ServiceReference1.StatusDTO status) {
            base.Channel.RemoveStatus(status);
        }
        
        public System.Threading.Tasks.Task RemoveStatusAsync(EX.Client.ServiceReference1.StatusDTO status) {
            return base.Channel.RemoveStatusAsync(status);
        }
        
        public EX.Client.ServiceReference1.StatusDTO[] GetAllStatuses() {
            return base.Channel.GetAllStatuses();
        }
        
        public System.Threading.Tasks.Task<EX.Client.ServiceReference1.StatusDTO[]> GetAllStatusesAsync() {
            return base.Channel.GetAllStatusesAsync();
        }
        
        public void AddUserInRole(EX.Client.ServiceReference1.UserInRoleDTO userInRoleDTO) {
            base.Channel.AddUserInRole(userInRoleDTO);
        }
        
        public System.Threading.Tasks.Task AddUserInRoleAsync(EX.Client.ServiceReference1.UserInRoleDTO userInRoleDTO) {
            return base.Channel.AddUserInRoleAsync(userInRoleDTO);
        }
        
        public void RemoveUserInRole(EX.Client.ServiceReference1.UserInRoleDTO userInRoleDTO) {
            base.Channel.RemoveUserInRole(userInRoleDTO);
        }
        
        public System.Threading.Tasks.Task RemoveUserInRoleAsync(EX.Client.ServiceReference1.UserInRoleDTO userInRoleDTO) {
            return base.Channel.RemoveUserInRoleAsync(userInRoleDTO);
        }
        
        public EX.Client.ServiceReference1.UserInRoleDTO[] GetAllUserInRole() {
            return base.Channel.GetAllUserInRole();
        }
        
        public System.Threading.Tasks.Task<EX.Client.ServiceReference1.UserInRoleDTO[]> GetAllUserInRoleAsync() {
            return base.Channel.GetAllUserInRoleAsync();
        }
        
        public void AddUser(EX.Client.ServiceReference1.UserDTO userDTO) {
            base.Channel.AddUser(userDTO);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(EX.Client.ServiceReference1.UserDTO userDTO) {
            return base.Channel.AddUserAsync(userDTO);
        }
        
        public void RemoveUser(EX.Client.ServiceReference1.UserDTO userDTO) {
            base.Channel.RemoveUser(userDTO);
        }
        
        public System.Threading.Tasks.Task RemoveUserAsync(EX.Client.ServiceReference1.UserDTO userDTO) {
            return base.Channel.RemoveUserAsync(userDTO);
        }
        
        public EX.Client.ServiceReference1.UserDTO[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<EX.Client.ServiceReference1.UserDTO[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
    }
}
